[tool.poetry]
name = "trig-functions"
version = "0.1.0"
description = ""
authors = ["Quincy Cambrel"]

[tool.poetry.dependencies]
python = "^3.8"
scipy = "^1.6.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
